# -*- coding: utf-8 -*-
"""constants.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3jIY-npi8C12fAE3Rdlndhv2ZDd89ik
"""

openai_key="sk-oLQH1QdeniDC4-ateIoizqByI5L50StJaWGB0MQdmtT3BlbkFJdP1gfFkhoollwTcADtyBb-y39dzeesEA0H8gVPDr8A"

