# -*- coding: utf-8 -*-
"""constants.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3jIY-npi8C12fAE3Rdlndhv2ZDd89ik
"""

openai_key="sk-RCHtAg9mZVzCimHMG1rUANiNxpglj5Y4DeipuDb3s4T3BlbkFJ0yDQ89MG3sCLR0d-JmKIazuRg0R7p8Nha_XZ30bHMA"

